DCC-5118
icgc-dcc/dcc-release pull request #19
Opened 2017-08-30 14:46 UTC by grant-guo

Assign ES document index tasks and tar creation tasks to different executor pools

2017-09-08 20:19 UTC, andricDu requested changes

2017-09-08 20:19 UTC, andricDu commented on dcc-release-job/dcc-release-job-index/src/main/java/org/icgc/dcc/release/job/index/core/IndexJob.java
> +//    val noBigFilesTasks = allTasks.stream()
What happened to the big files task?

2017-09-13 17:23 UTC, andricDu commented
We are going to test a full document + index and then merge if successful.

2017-09-13 20:58 UTC, grant-guo commented
ok to test

2017-09-18 13:52 UTC, grant-guo commented
ok to test

2017-09-20 13:50 UTC, andricDu approved these changes

2017-09-20 13:50 UTC, merged